#!/bin/bash

rm -rvf *-10m.json *-50m.json *-110m.json
mkdir -p build

countries_shp() {
  if [ ! -f build/ne_$1_admin_0_countries.shp ]; then
    curl -o build/ne_$1_admin_0_countries.zip https://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
    unzip -od build build/ne_$1_admin_0_countries.zip
    chmod a-x build/ne_$1_admin_0_countries.*
  fi
}

world() {
  countries_shp $1
  geo2topo -q 1e5 -n countries=<( \
      shp2json --encoding utf8 -n build/ne_$1_admin_0_countries.shp \
        | ndjson-map 'i = d.properties.ISO_N3, d.id = i === "-99" ? (d.properties.SOV_A3 === "NOR" ? "578" : undefined) : i, d.properties = {name: d.properties.NAME}, d' \
        | ndjson-filter '!d.properties.name.startsWith("Antarctica")' \
        | geostitch -n) \
    | topomerge land=countries \
    > world-$1.json
}

world 110m
